### ISSUE TITLE
There is a space between ">" and the sequence name in FASTA header

### ISSUE THREAD

**Issue by quwubin** [mauriceling/bactome#11]
Hi,

When using this command: 

`randomseq.py MS --n=10 --cap_start=False --cap_stop=False --selection="A,250;T,250;G,250;C,250" --fasta=True --statement="c(gtaag);v(10,15,False,False,False,False);c(gtccg);v(20,30,False,False,False,False)"`,

there is a space between ">" and the sequence name in FASTA header:

e.g., 

```bash
> Test_1
gtaagGCAAATACCGCAgtccgTTTCCAGGCTTCACCCGCCAGT
> Test_2
gtaagACGTTCCACGGGAAAgtccgAACTACACTTCCGAACCATATAC
> Test_3
gtaagTGGACGTCCCCAgtccgGCACCCGGACGCAACGGAGAGTTA
```

Fixed this by changing the code `print("> %s" % title)` to `print(">%s" % title)`:

```bash
>Test_1
gtaagGGTGTCGACATCCgtccgCACCTCTCTCGACAGGTCCTACAGCGA
>Test_2
gtaagGCACCAATCATgtccgGGTCTATTCAAAAAAACCGGA
>Test_3
gtaagTCAAAGAGGGGGgtccgGTCAAGGGAAATACCCCTTCATCTT
```

**Comment by mauriceling** [comment]
Thanks a lot - Amended - https://github.com/mauriceling/bactome/commit/1ea38d8dc3517579c8054916373030fe1b9c84c9
