### ISSUE TITLE
Suggesting fix of casting a boolean to `.lower()` in randomseq.py

### ISSUE THREAD

**Issue by fomightez** [mauriceling/bactome#6]
I think maybe something changed in Fire or there are differences in Python 3, but with the current `randomseq.py` code, I always get an error `AttributeError: 'bool' object has no attribute 'lower'`.
Casting it to a string or removing the first part all together since it should be a boolean fixes it.

I suggest changing lines 263 and 265 in `randomseq.py` to either of the following:

    if str(cap_start).lower() == 'true' or cap_start == True:
    if str(cap_stop).lower() == 'true' or cap_stop == True:

-or-

    if  cap_start == True:
    if cap_stop == True:

----

If you want to see it not working for yourself, launch a fresh Python system by clicking on the `launch binder` badge [here](https://github.com/fomightez/cl_sq_demo-binder). And then  paste the following code in a cell and hit shift-enter to run it.

    !pip install fire
    !curl -O https://raw.githubusercontent.com/mauriceling/bactome/master/randomseq.py
    !python randomseq.py FLS --length=1306 --n=1 --allow_start=True --allow_stop=True

No matter what `allow_start` and `allow_stop` are set to, and even if they aren't included, you encounter the error.

**Comment by mauriceling** [comment]
I've changed as per suggested (https://github.com/mauriceling/bactome/commit/ef9182e012def40399428ca7a34ed6cb1458f42e) - can you give it a try?

May I also know how you are using randomseq.py?

**Comment by fomightez** [comment]
Thanks! That fixed it. My notebook now points at your repo for obtaining the script.

Sorry, no exciting use case to report yet. Looked like a handy script, and so by using it for anything I'll be more likely to remember it when I need something similar for a real workflow.  For now I just wanted to generate a multi-record FASTA file easily for documenting use of a simple utility script I wrote. You can see it in action at https://github.com/fomightez/cl_sq_demo-binder . Go there and click the `launch binder` badge. Then when the session spins up, select the notebook 'Demo of script to get specified length of sequence from end of a record in FASTA file' from the list.   Your script first gets used in the third cell. You can use the menu to  run all the cells to see it actually run the code.
